### ISSUE TITLE
ADLS Gen2 - Error when selecting the filesystem-name aka container-name

### ISSUE THREAD

**Issue by manimaranm7** [aloneguid/StorAMP#1]
After an ADLS Gen2 account is added, the explorer pane displays the container-name aka filesystem. Clicking on it (single click) tries to bring up it's properties in right hand side pane. Because this is the filesystem folder, an error is displayed when attempting to display the properties of this folder as shown below:

![image](https://user-images.githubusercontent.com/6642107/63707955-156b1900-c82b-11e9-8677-bd5b03740c02.png)

One of the ideas could be to accept the name of the filesystem when adding the ADLS Gen2 account and default the explorer pane to this folder.

Another idea could be to detect that it is an ADLS Gen2 account and not allow any operations on the filesystem folder - need not be fancy, just don't try to show the properties of container-name in the right hand side pane.

**Comment by aloneguid** [comment]
The fix is already rolling out. Unfortunately windows 10 store accepts updates only during business days, wait till Wednesday )

**Comment by manimaranm7** [comment]
Was fixed in version 1.2.2
