### ISSUE TITLE
ADLS Gen2 - Use a unique icon to identify ADLS Gen2 tab

### ISSUE THREAD

**Issue by manimaranm7** [aloneguid/StorAMP#2]
Right now, both ADLS Gen2 and Blob Storage accounts use same icon in the tab (as well as when adding accounts). I am aware that Gen2 is basically Storage Account + Hierarchical Namespace, but for a UX perspective it will help to distinguish this.

May be a miniaturised version of the icon on this image? 
![image](https://user-images.githubusercontent.com/6642107/63708714-1ac96300-c82d-11e9-8432-b0fcf6357dde.png)

**Comment by aloneguid** [comment]
Yeah good idea, will include in the next update.

**Comment by manimaranm7** [comment]
Was fixed in version 1.2.3
