### ISSUE TITLE
UX improvements - more padding, group toolbar icons

### ISSUE THREAD

**Issue by manimaranm7** [aloneguid/StorAMP#3]
It might help if there is more padding around the buttons in the toolbar. They appear to be too close and can cause accidental press. Also if possible, please increase padding below tabs and above toolbar.

Also, it might be better to separate the buttons into multiple toolbars side by side (only if possible). The "refresh", "go up" and "view" can be grouped as one. The "new folder" and "delete" should be in separate groups and as far away as possible to avoid accidental press.

The main application icon can be made transparent because it does not look great with any of the themes. 
![image](https://user-images.githubusercontent.com/6642107/63709738-6b41c000-c82f-11e9-9dc2-a8ea88688e2a.png)

This free app might help to get vector/xaml icons (I used to use it long ago when designing Win Phone apps): https://www.syncfusion.com/downloads/metrostudio

**Comment by aloneguid** [comment]
It's using vector icons at the moment for everything, no bitmaps anywhere. I could make a configuration setting for toolbar size I guess, all the graphics is scalable.
